export const linkedinLink = "https://www.linkedin.com/in/sanjampreetsingh/";
export const twitterLink = "https://twitter.com/sanjampreet_";
export const youtubeLink = "https://www.youtube.com/@CodeSanjam";
export const instagramLink = "https://www.instagram.com/code_sanjam/";
export const githubLink = "https://github.com/SanjampreetSingh/";
export const bcgXLink = "https://www.bcg.com/x";
export const accentureLink = "https://www.accenture.com/in-en";
export const infosysLink = "https://www.infosys.com/";
export const gndecLink = "https://www.gndec.ac.in/";
export const emailLink = "sanjam531@gmail.com";
export const resumeLink =
  "https://drive.google.com/file/d/19ZHOS1je3u2HA7U9XyrD7s2f_txp_sak/view?usp=sharing";
